src/AppBundle/Entity/ForumBan.php
<?php

namespace AppBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Ramsey\Uuid\Uuid;

/**
 * Represents a ban or unban action that applies to a user and a forum.
 *
 * @ORM\Entity(repositoryClass="AppBundle\Repository\ForumBanRepository")
 * @ORM\Table(name="forum_bans")
 */
class ForumBan {
    /**
     * @ORM\Column(type="uuid")
     * @ORM\Id()
     *
     * @var Uuid
     */
    private $id;

    /**
     * @ORM\JoinColumn(nullable=false)
     * @ORM\ManyToOne(targetEntity="Forum", inversedBy="bans")
     *
     * @var Forum
     */
    private $forum;

    /**
     * @ORM\JoinColumn(nullable=false)
     * @ORM\ManyToOne(targetEntity="User")
     *
     * @var User
     */
    private $user;

    /**
     * @ORM\Column(type="text")
     *
     * @var string
     */
    private $reason;

    /**
     * @ORM\Column(type="boolean")
     *
     * @var bool
     */
    private $banned;

    /**
     * @ORM\JoinColumn(nullable=false)
     * @ORM\ManyToOne(targetEntity="User")
     *
     * @var User
     */
    private $bannedBy;

    /**
     * @ORM\Column(type="datetimetz")
     *
     * @var \DateTime
     */
    private $timestamp;

    /**
     * @ORM\Column(type="datetimetz", nullable=true)
     */
    private $expiresAt;

    public function __construct(
        Forum $forum,
        User $user,
        string $reason,
        bool $banned,
        User $bannedBy,
        \DateTime $expiresAt = null,
        \DateTime $timestamp = null
    ) {
        if (!$banned && $expiresAt) {
            throw new \DomainException('Unbans cannot have expiry times');
        }

        $this->id = Uuid::uuid4();
        $this->forum = $forum;
        $this->user = $user;
        $this->reason = $reason;
        $this->banned = $banned;
        $this->bannedBy = $bannedBy;
        $this->expiresAt = $expiresAt;

        // since the last ban takes precedence, and because timestamps are used
        // for sorting, we'll use microseconds to hopefully avoid collisions
        $this->timestamp = $timestamp ?:
            \DateTime::createFromFormat('U.u', microtime(true));
    }

    public function getId(): Uuid {
        return $this->id;
    }

    public function getForum(): Forum {
        return $this->forum;
    }

    public function getUser(): User {
        return $this->user;
    }

    public function getReason(): string {
        return $this->reason;
    }

    public function isBan(): bool {
        return $this->banned;
    }

    public function getBannedBy(): User {
        return $this->bannedBy;
    }

    public function getTimestamp(): \DateTime {
        return $this->timestamp;
    }

    /**
     * @return \DateTime|null
     */
    public function getExpiryTime() {
        return $this->expiresAt;
    }

    public function isExpired() {
        if ($this->expiresAt === null) {
            return false;
        }

        return $this->expiresAt < \DateTime::createFromFormat('U.u', microtime(true));
    }
}

src/AppBundle/Entity/User.php
<?php

namespace AppBundle\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\Criteria;
use Doctrine\Common\Collections\Selectable;
use Doctrine\ORM\Mapping as ORM;
use Pagerfanta\Adapter\DoctrineCollectionAdapter;
use Pagerfanta\Adapter\DoctrineSelectableAdapter;
use Pagerfanta\Pagerfanta;
use Symfony\Component\Security\Core\User\EquatableInterface;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass="AppBundle\Repository\UserRepository")
 * @ORM\Table(name="users")
 */
class User implements UserInterface, EquatableInterface {
    const FRONT_DEFAULT = 'default';
    const FRONT_FEATURED = 'featured';
    const FRONT_SUBSCRIBED = 'subscribed';
    const FRONT_ALL = 'all';
    const FRONT_MODERATED = 'moderated';

    const FRONT_PAGE_CHOICES = [
        self::FRONT_DEFAULT,
        self::FRONT_FEATURED,
        self::FRONT_SUBSCRIBED,
        self::FRONT_ALL,
        self::FRONT_MODERATED,
    ];

    /**
     * @ORM\Column(type="bigint")
     * @ORM\GeneratedValue(strategy="AUTO")
     * @ORM\Id()
     *
     * @var int|null
     */
    private $id;

    /**
     * @ORM\Column(type="text", unique=true)
     *
     * @var string
     */
    private $username;

    /**
     * @ORM\Column(type="text", unique=true)
     *
     * @var string
     */
    private $canonicalUsername;

    /**
     * @ORM\Column(type="text")
     *
     * @var string
     */
    private $password;

    /**
     * @ORM\Column(type="text", nullable=true)
     *
     * @var string|null
     */
    private $email;

    /**
     * @ORM\Column(type="text", nullable=true)
     *
     * @var string|null
     */
    private $canonicalEmail;

    /**
     * @ORM\Column(type="datetimetz")
     *
     * @var \DateTime
     */
    private $created;

    /**
     * @ORM\Column(type="datetimetz", nullable=true)
     *
     * @var \DateTime|null
     */
    private $lastSeen;

    /**
     * @ORM\Column(type="boolean", options={"default": false})
     *
     * @var bool
     */
    private $admin = false;

    /**
     * @ORM\OneToMany(targetEntity="Moderator", mappedBy="user")
     *
     * @var Moderator[]|Collection
     */
    private $moderatorTokens;

    /**
     * @ORM\OneToMany(targetEntity="Submission", mappedBy="user")
     * @ORM\OrderBy({"id": "DESC"})
     *
     * @var Submission[]|Collection|Selectable
     */
    private $submissions;

    /**
     * @ORM\OneToMany(targetEntity="Comment", mappedBy="user")
     * @ORM\OrderBy({"id": "DESC"})
     *
     * @var Comment[]|Collection|Selectable
     */
    private $comments;

    /**
     * @ORM\OneToMany(targetEntity="UserBan", mappedBy="user")
     *
     * @var UserBan[]|Collection|Selectable
     */
    private $bans;

    /**
     * @ORM\OneToMany(targetEntity="IpBan", mappedBy="user")
     *
     * @var IpBan[]|Collection|Selectable
     */
    private $ipBans;

    /**
     * @ORM\Column(type="text")
     *
     * @var string
     */
    private $locale = 'en';

    /**
     * @ORM\OneToMany(targetEntity="Notification", mappedBy="user", fetch="EXTRA_LAZY", cascade={"persist"})
     *
     * @var Notification[]|Collection|Selectable
     */
    private $notifications;

    /**
     * @ORM\Column(type="boolean")
     *
     * @var bool
     */
    private $nightMode = false;

    /**
     * @ORM\Column(type="boolean", options={"default": true})
     *
     * @var bool
     */
    private $showCustomStylesheets = true;

    /**
     * @ORM\Column(type="boolean", options={"default": false})
     *
     * @var bool
     */
    private $trusted = false;

    /**
     * @ORM\ManyToOne(targetEntity="Theme")
     *
     * @var Theme|null
     */
    private $preferredTheme;

    /**
     * @ORM\OneToMany(targetEntity="UserBlock", mappedBy="blocker")
     * @ORM\OrderBy({"timestamp": "DESC"})
     *
     * @var UserBlock[]|Collection|Selectable
     */
    private $blocks;

    /**
     * @ORM\Column(type="text", options={"default": "default"})
     *
     * @var string
     */
    private $frontPage = self::FRONT_DEFAULT;

    /**
     * @ORM\Column(type="boolean", options={"default": false})
     *
     * @var bool
     */
    private $openExternalLinksInNewTab = false;

    /**
     * @ORM\Column(type="text", nullable=true)
     *
     * @var string|null
     */
    private $biography;

    public function __construct(string $username, string $password, \DateTime $created = null) {
        $this->setUsername($username);
        $this->password = $password;
        $this->created = $created ?: new \DateTime('@'.time());
        $this->notifications = new ArrayCollection();
        $this->submissions = new ArrayCollection();
        $this->comments = new ArrayCollection();
        $this->bans = new ArrayCollection();
        $this->ipBans = new ArrayCollection();
        $this->blocks = new ArrayCollection();
    }

    /**
     * @return int|null
     */
    public function getId() {
        return $this->id;
    }

    public function getUsername(): string {
        return $this->username;
    }

    public function setUsername(string $username) {
        $this->username = $username;
        $this->canonicalUsername = self::canonicalizeUsername($username);
    }

    public function getCanonicalUsername(): string {
        return $this->canonicalUsername;
    }

    public function getPassword(): string {
        return $this->password;
    }

    public function setPassword(string $password) {
        $this->password = $password;
    }

    /**
     * @return string|null
     */
    public function getEmail() {
        return $this->email;
    }

    /**
     * @param string|null $email
     */
    public function setEmail($email) {
        $this->email = $email;
        $this->canonicalEmail = $email ? self::canonicalizeEmail($email) : null;
    }

    /**
     * Retrieve the canonical email address.
     *
     * Sending email to the canonicalised address is evil. Use this for lookup,
     * but *always* send to the regular, non-canon address.
     *
     * @return string|null
     */
    public function getCanonicalEmail() {
        return $this->canonicalEmail;
    }

    public function getCreated(): \DateTime {
        return $this->created;
    }

    /**
     * @return \DateTime|null
     */
    public function getLastSeen() {
        return $this->lastSeen;
    }

    /**
     * @param \DateTime|null $lastSeen
     */
    public function setLastSeen($lastSeen) {
        $this->lastSeen = $lastSeen;
    }

    public function isAdmin(): bool {
        return $this->admin;
    }

    public function setAdmin(bool $admin) {
        $this->admin = $admin;
    }

    /**
     * @return Collection|Moderator[]
     */
    public function getModeratorTokens(): Collection {
        return $this->moderatorTokens;
    }

    /**
     * {@inheritdoc}
     */
    public function getRoles() {
        $roles = ['ROLE_USER'];

        if ($this->admin) {
            $roles[] = 'ROLE_ADMIN';
        }

        if ($this->trusted) {
            $roles[] = 'ROLE_TRUSTED_USER';
        }

        return $roles;
    }

    /**
     * {@inheritdoc}
     */
    public function getSalt() {
        // Salt is not needed when bcrypt is used, as the password hash contains
        // the salt.
        return null;
    }

    /**
     * {@inheritdoc}
     */
    public function eraseCredentials() {
    }

    /**
     * @return Collection|Selectable|Submission[]
     */
    public function getSubmissions(): Collection {
        return $this->submissions;
    }

    /**
     * @param int $page
     * @param int $maxPerPage
     *
     * @return Pagerfanta|Comment[]
     */
    public function getPaginatedSubmissions(int $page, int $maxPerPage = 25): Pagerfanta {
        $submissions = new Pagerfanta(new DoctrineCollectionAdapter($this->submissions));
        $submissions->setMaxPerPage($maxPerPage);
        $submissions->setCurrentPage($page);

        return $submissions;
    }

    /**
     * @return Collection|Selectable|Comment[]
     */
    public function getComments(): Collection {
        return $this->comments;
    }

    /**
     * @param int $page
     * @param int $maxPerPage
     *
     * @return Pagerfanta|Comment[]
     */
    public function getPaginatedComments(int $page, int $maxPerPage = 25): Pagerfanta {
        $comments = new Pagerfanta(new DoctrineCollectionAdapter($this->comments));
        $comments->setMaxPerPage($maxPerPage);
        $comments->setCurrentPage($page);

        return $comments;
    }

    /**
     * @return UserBan[]|Collection
     */
    public function getBans(): Collection {
        return $this->bans;
    }

    public function addBan(UserBan $ban) {
        if (!$this->bans->contains($ban)) {
            $this->bans->add($ban);
        }
    }

    public function isBanned(): bool {
        $criteria = Criteria::create()
            ->orderBy(['timestamp' => 'DESC'])
            ->setMaxResults(1);

        /* @var UserBan $ban */
        $ban = $this->bans->matching($criteria)->first() ?: null;

        return $ban && $ban->isBan() && !$ban->isExpired();
    }

    /**
     * @return Collection|IpBan[]
     */
    public function getIpBans(): Collection {
        return $this->ipBans;
    }

    public function getLocale(): string {
        return $this->locale;
    }

    public function setLocale(string $locale) {
        $this->locale = $locale;
    }

    /**
     * @return Collection|Selectable|Notification[]
     */
    public function getNotifications(): Collection {
        return $this->notifications;
    }

    public function sendNotification(Notification $notification) {
        if (!$this->notifications->contains($notification)) {
            $this->notifications->add($notification);
        }
    }

    /**
     * @param int $page
     * @param int $maxPerPage
     *
     * @return Pagerfanta|Notification[]
     */

src/AppBundle/Form/ForumType.php
<?php

namespace AppBundle\Form;

use AppBundle\Form\Type\HoneypotType;
use Doctrine\ORM\EntityRepository;
use AppBundle\Entity\ForumCategory;
use AppBundle\Form\Model\ForumData;
use AppBundle\Form\Type\MarkdownType;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\FormInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Security\Core\Authorization\AuthorizationCheckerInterface;

final class ForumType extends AbstractType {
    /**
     * @var AuthorizationCheckerInterface
     */
    private $authorizationChecker;

    public function __construct(AuthorizationCheckerInterface $authorizationChecker) {
        $this->authorizationChecker = $authorizationChecker;
    }

    /**
     * {@inheritdoc}
     */
    public function buildForm(FormBuilderInterface $builder, array $options) {
        if ($options['honeypot']) {
            $builder->add('email', HoneypotType::class);
        }

        /* @var ForumData $data */
        $data = $builder->getData();
        $editing = $data && $data->getEntityId();

        $builder
            ->add('name', TextType::class)
            ->add('title', TextType::class)
            ->add('description', TextareaType::class)
            ->add('sidebar', MarkdownType::class, [
                'label' => 'label.sidebar',
            ])
            ->add('category', EntityType::class, [
                'class' => ForumCategory::class,
                'choice_label' => 'name',
                'query_builder' => function (EntityRepository $repository) {
                    return $repository->createQueryBuilder('fc')
                        ->orderBy('fc.name', 'ASC');
                },
                'required' => false,
                'placeholder' => 'forum_form.uncategorized_placeholder',
            ])
        ;

        if ($this->authorizationChecker->isGranted('ROLE_ADMIN')) {
            $builder->add('featured', CheckboxType::class, [
                'required' => false,
            ]);
        }

        $builder->add('submit', SubmitType::class, [
            'label' => $editing ? 'forum_form.save' : 'forum_form.create',
        ]);
    }

    /**
     * {@inheritdoc}
     */
    public function configureOptions(OptionsResolver $resolver) {
        $resolver->setDefaults([
            'data_class' => ForumData::class,
            'label_format' => 'forum_form.%name%',
            'honeypot' => true,
            'validation_groups' => function (FormInterface $form) {
                $editing = $form->getData() && $form->getData()->getEntityId();

                return $editing ? ['edit'] : ['create'];
            },
        ]);

        $resolver->setAllowedTypes('honeypot', ['bool']);
    }
}

templates/forum/_list_macros.html.twig
{% macro forum_list_header() %}
  <nav class="tabs forum-list-view-selector">
    <ul class="tabs__bar">
      {% with { active: app.request.attributes.get('_route') == 'forum_list' } %}
        <li class="tabs__tab {{ active ? 'tabs__tab--active active' }}">
          <a href="{{ path('forum_list') }}" class="tabs__link {{ active ? 'tabs__link--active' }}">
            {{- 'forum_list.list_view'|trans -}}
          </a>
        </li>
      {% endwith %}
      {% with { active: app.request.attributes.get('_route') == 'forums_by_category' } %}
        <li class="tabs__tab {{ active ? 'tabs__tab--active active' }}">
          <a href="{{ path('forums_by_category') }}" class="tabs__link {{ active ? 'tabs__link--active' }}">
            {{- 'forum_list.category_view'|trans -}}
          </a>
        </li>
      {% endwith %}
    </ul>
  </nav>

  <h1 class="page-heading">{{ 'forum_list.page_title'|trans }}</h1>

  {% if is_granted('create_forum') %}
    <p role="navigation">
      <a href="{{ path('create_forum') }}" class="button">{{ 'forum_list.create_forum'|trans }}</a>
    </p>
  {% elseif is_granted('ROLE_USER') %}
    <div class="alert alert--notice">
      <p>{{ 'flash.you_cannot_create_forums_yet'|trans }}</p>
    </div>
  {% endif %}
{% endmacro %}

templates/forum/add_moderator.html.twig
{% extends 'forum/base.html.twig' %}

{% block page_classes %}
  add-moderators-page
{% endblock %}

{% block title %}
  {{ 'add_moderator.title'|trans({'%forum%': forum.name}) }}
{% endblock %}

{% block body %}
  <h1 class="page-heading">{{ block('title') }}</h1>

  {{ form(form) }}
{% endblock %}

templates/forum/appearance.html.twig
{% extends 'forum/base.html.twig' %}

{% block title 'title.forum_appearance'|trans({'%forum%': '/f/%s'|format(forum.name)}) %}
{% block page_classes 'forum-appearance-page' %}

{% block body %}
  <h1 class="page-heading">
    {{ 'title.forum_appearance'|trans({'%forum%': '<a href="%s">/f/%s</a>'|format(
      path('forum', {forum_name: forum.name})|escape,
      forum.name|escape
    )})|raw }}
  </h1>

  {{ form_start(form) }}
    {{ form_row(form.theme, {attr: {class: 'select2'}}) }}

    {# todo: some navigation widget thing #}
    <nav>
      <ul>
        <li><a href="{{ path('themes') }}">{{ 'nav.themes'|trans }}</a></li>
        <li><a href="{{ path('create_theme') }}">{{ 'nav.create_theme'|trans }}</a></li>
      </ul>
    </nav>
  {{ form_end(form) }}
{% endblock %}

templates/forum/ban_history.html.twig
{% extends 'forum/base.html.twig' %}

{% block page_classes 'forum-ban-history-page' %}
{% block title 'title.showing_ban_history_for_user_in_forum'|trans({
  '%user%': '/u/'~user.username,
  '%forum%': '/f/'~forum.name,
}) %}

{% block head %}
  {{ parent() }}
  {{ include('_includes/meta_pagination.html.twig', {pager: bans}, with_context=false) }}
{% endblock %}

{% block body %}
  <h1 class="page-heading">{{ block('title') }}</h1>

  <table class="table">
    <thead>
      <tr>
        <th>{{ 'label.action'|trans }}</th>
        <th>{{ 'label.reason'|trans }}</th>
        <th>{{ 'label.banned'|trans }}</th>
        <th>{{ 'label.expires'|trans }}</th>
      </tr>
    </thead>
    <tbody>
      {% for ban in bans %}
        <tr>
          <td>{{ (ban.ban ? 'label.ban' : 'label.unban')|trans }}</td>
          <td>{{ ban.reason }}</td>
          <td>
            {% with {date: ban.timestamp|localizeddate('long', 'short')} %}
              <time datetime="{{ ban.timestamp|date('c') }}" class="relative-time" title="{{ date }}">
                {{- date -}}
              </time>
            {% endwith %}
          </td>
          <td>
            {% if ban.expiryTime %}
              {% with {date: ban.expiryTime|localizeddate('long', 'short')} %}
                <time datetime="{{ ban.expiryTime|date('c') }}" class="relative-time" title="{{ date }}">
                  {{- date -}}
                </time>
              {% endwith %}
            {% else %}
              {{ 'label.never'|trans }}
            {% endif %}
          </td>
        </tr>
      {% endfor %}
    </tbody>
  </table>

  {{ include('_includes/pagination.html.twig', {pager: bans}, with_context=false) }}
{% endblock %}

templates/forum/base.html.twig
{% extends 'base.html.twig' %}

{% block head %}
  <link rel="alternate" type="application/atom+xml" href="{{ path('forum_feed', {forum_name: forum.name}) }}" title="{{ forum.name }}">
{% endblock %}

{% block stylesheets %}
  {% if (app.user.showCustomStylesheets ?? true) and forum.theme %}
    {{ include('_includes/stylesheets.html.twig', {
      theme: forum.theme,
      night_mode: app.user.nightMode ?? false
    }, with_context=false) }}
  {% else %}
    {{ parent() }}
  {% endif %}
{% endblock %}

{% block sidebar %}
  <section class="sidebar__section sidebar__section--forum-meta forum-meta">
    <h1 class="sidebar__title forum-title"><a href="{{ path('forum', {forum_name: forum.name}) }}">{{ forum.title }}</a></h1>

    {% if is_granted('ROLE_USER') %}
      {% from 'forum/_macros.html.twig' import subscribe_button %}
      {% set subscribed = forum.subscribed(app.user) %}
      <form action="{{ path(subscribed ? 'unsubscribe' : 'subscribe', {forum_name: forum.name}) }}" method="POST" class="form">
        <input type="hidden" name="token" value="{{ csrf_token('subscribe') }}">

        <div class="form__row">
          {{ subscribe_button(forum, subscribed, false) }}
        </div>
      </form>
    {% endif %}

    {% if forum.sidebar is not empty %}
      <div class="forum-sidebar-content">{{ forum.sidebar|cached_markdown|raw }}</div>
    {% endif %}
  </section>

  <section class="sidebar__section sidebar__section--forum-manage forum-manage">
    <h1 class="sidebar__title">{{ 'label.toolbox'|trans }}</h1>

    {# sorted nav items #}
    {% with { items: {} } %}
      {% set item %}
        <li><a href="{{ path('forum_bans', {forum_name: forum.name}) }}">{{ 'nav.bans'|trans }}</a></li>
      {% endset %}
      {% set items = items|merge({('nav.bans'|trans): item}) %}

      {% set item %}
        <li><a href="{{ path('moderation_log', {forum_name: forum.name}) }}">{{ 'nav.moderation_log'|trans }}</a></li>
      {% endset %}
      {% set items = items|merge({('nav.moderation_log'|trans): item}) %}

      {% if is_granted('moderator', forum) %}
        {% set item %}
          <li><a href="{{ path('edit_forum', {forum_name: forum.name}) }}">{{ 'forum.edit'|trans }}</a></li>
        {% endset %}
        {% set items = items|merge({('forum.edit'|trans): item}) %}

        {% set item %}
          <li><a href="{{ path('forum_appearance', {forum_name: forum.name}) }}">{{ 'nav.appearance'|trans }}</a></li>
        {% endset %}
        {% set items = items|merge({('nav.appearance'|trans): item}) %}
      {% endif %}

      {% if is_granted('ROLE_ADMIN') %}
        {% set item %}
          <li><a href="{{ path('add_moderator', {forum_name: forum.name}) }}">{{ 'forum.add_moderator'|trans }}</a></li>
        {% endset %}
        {% set items = items|merge({('forum.add_moderator'|trans): item}) %}

        {% set item %}
          <li><a href="{{ path('delete_forum', {forum_name: forum.name}) }}">{{ 'nav.delete_forum'|trans }}</a></li>
        {% endset %}
        {% set items = items|merge({('nav.delete_forum'|trans): item}) %}
      {% endif %}

      <ul>
        {% for key in items|keys|sort %}
          {{ items[key] }}
        {% endfor %}
      </ul>
    {% endwith %}
  </section>

  {% if forum.moderators|length > 0 %}
    <section class="sidebar__section sidebar__section--forum-moderators forum-moderators">
      <h1 class="sidebar__title"><a href="{{ path('forum_moderators', {forum_name: forum.name}) }}">{{ 'forum.moderators'|trans }}</a></h1>
      <ul>
        {% for moderator in forum.moderators %}
          <li>
            <a href="{{ path('user', {username: moderator.user.username}) }}">
              {{- moderator.user.username -}}
            </a>
          </li>
        {% endfor %}
      </ul>
    </section>
  {% endif %}
{% endblock %}

templates/forum/delete.html.twig
{% extends 'forum/base.html.twig' %}

{% block title 'title.delete_forum'|trans({'%forum%': '/f/%s'|format(forum.name)}) %}
{% block page_classes 'forum-delete-page' %}

{% block body %}
  <h1 class="page-heading">
    {{- 'title.delete_forum'|trans({'%forum%': '<a href="%s">/f/%s</a>'|format(
      path('forum', {forum_name: forum.name})|escape,
      forum.name|escape
      )})|raw
    -}}
  </h1>

  <p>{{ 'help.delete_forum_warning'|trans }}</p>

  {{ form(form) }}
{% endblock %}

templates/forum/edit.html.twig
{% extends 'forum/base.html.twig' %}

{% block page_classes %}edit-forum-page{% endblock %}
{% block title 'edit_forum.title'|trans({'%forum%': '/f/'~forum.name}) %}

{% block body %}
  <h1 class="page-heading">
    {{ 'title.editing_forum'|trans({
      '%forum%': '<a href="%s">/f/%s</a>'|format(path('forum', {forum_name: forum.name})|e, forum.name|e)
    })|raw }}
  </h1>

  {{ include('forum/_form.html.twig', {form: form}, with_context=false) }}
{% endblock %}

{% block javascripts %}
  {{ parent() }}

  <script>
    $('.delete-forum').click(function () {
      return confirm(Translator.trans('forum_form.confirm_delete'));
    });
  </script>
{% endblock %}

templates/forum/forum.html.twig
{% extends 'forum/base.html.twig' %}

{% from 'submission/_macros.html.twig' import submission, submission_sort %}

{% block title %}{{ forum.title }}{% endblock %}

{% block head %}
  {{ parent() }}

  <link rel="canonical" href="{{ url('forum', {forum_name: forum.name}) }}">
  {% include '_includes/meta_pagination.html.twig' with {pager: submissions} %}

  <meta property="og:title" content="{{ forum.title }}">
  <meta property="og:site_name" content="{{ site_name() }}">
  <meta property="og:type" content="website">
  <meta property="og:url" content="{{ url('forum', {forum_name: forum.name}) }}">
  <meta property="og:image" content="{{ absolute_url(asset('apple-touch-icon-precomposed.png')) }}">

  {% if forum.description is not empty %}
    <meta name="description" content="{{ forum.description }}">
  {% endif %}
{% endblock %}

{% block page_classes %}forum-front{% endblock %}

{% block body %}
  {% spaceless %}
    <h1 class="page-heading forum-name-heading">
      <span class="forum-name-heading__prefix">/f/</span>
      <strong class="forum-name-heading__name">{{ forum.name }}</strong>
    </h1>
  {% endspaceless %}

  <nav class="tabs submission-sort">
    <ul class="tabs__bar">
      {{- submission_sort(sort_by) -}}
    </ul>
  </nav>

  {% for submission in submissions %}
    {{ submission(submission, {show_forum_name: false}) }}
  {% endfor %}

  {% include '_includes/pagination.html.twig' with {pager: submissions} %}
{% endblock %}

templates/forum/unban.html.twig
{% extends 'forum/ban.html.twig' %}

{% block title 'title.unbanning_user_from_forum'|trans({
  '%user%': '/u/'~user.username,
  '%forum%': '/f/'~forum.name,
}) %}

{% block page_classes 'forum-unban-page' %}